In [1]:
import os
import pandas as pd

from src.conf import settings, COL_NAMES

In [2]:
inter_fnames = os.listdir(settings.paths.interactions_raw)
n_inter_fnames = len(inter_fnames)

In [3]:
df = pd.read_csv(settings.paths.interactions_raw / inter_fnames[28], delimiter="\t")
df.head(5)

C:\Users\epirt\AppData\Local\Temp\ipykernel_22504\2694766993.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(settings.paths.interactions_raw / inter_fnames[28], delimiter="\t")

,user_id,anime_id,favorite,review_id,review_date,review_num_useful,review_score,review_story_score,review_animation_score,review_sound_score,review_character_score,review_enjoyment_score,score,status,progress,last_interaction_date
0,k4kashii21,39486,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,completed,1.0,2021-01-08 00:00:00
1,k4kashii21,39523,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,completed,12.0,2019-12-19 00:00:00
2,k4kashii21,39534,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,completed,12.0,2020-03-27 00:00:00
3,k4kashii21,39535,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,completed,11.0,2021-03-22 00:00:00
4,k4kashii21,39545,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,completed,1.0,2019-11-22 00:00:00

In [4]:
inter_df_init = pd.read_csv(settings.paths.interactions_raw / inter_fnames[28], delimiter="\t")
inter_df_init[~inter_df_init["review_id"].isna()].head(5)

C:\Users\epirt\AppData\Local\Temp\ipykernel_22504\4001735171.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  inter_df_init = pd.read_csv(settings.paths.interactions_raw / inter_fnames[28], delimiter="\t")

,user_id,anime_id,favorite,review_id,review_date,review_num_useful,review_score,review_story_score,review_animation_score,review_sound_score,review_character_score,review_enjoyment_score,score,status,progress,last_interaction_date
8887,k4nr4,34382,0,269834.0,2018-01-27 00:00:00,20.0,7.0,7.0,8.0,6.0,7.0,7.0,7.0,watching,4.0,2018-01-27 00:00:00
8896,k4nr4,34561,1,258941.0,2017-09-28 00:00:00,7.0,8.0,7.0,8.0,9.0,8.0,10.0,8.0,completed,22.0,2017-09-28 00:00:00
11193,k4ori_,3588,0,364247.0,2020-11-16 00:00:00,0.0,6.0,5.0,6.0,8.0,7.0,4.0,6.0,completed,51.0,2020-11-16 00:00:00
11210,k4ori_,37517,0,393230.0,2021-04-19 00:00:00,0.0,6.0,5.0,6.0,6.0,5.0,6.0,6.0,completed,12.0,2021-04-19 00:00:00
11267,k4ori_,43299,0,389726.0,2021-04-05 00:00:00,2.0,8.0,8.0,10.0,8.0,9.0,9.0,8.0,completed,12.0,2021-04-05 00:00:00

In [5]:
from src.data_preprocessing import InteractionsPreprocessor

interactions_preprocessor = InteractionsPreprocessor(data_path=settings.paths.interactions_raw)
inter_full_df = interactions_preprocessor.preprocess_raw_interactions()

2025-02-23 19:53:01,830 | [INFO] User ids loaded from parquet file

Preprocessing: 100%|██████████| 70/70 [05:34<00:00,  5.28s/it]

2025-02-23 20:00:04,333 | [INFO] Interactions preprocessed, joining with user ids...

Preprocessing: 100%|██████████| 70/70 [08:05<00:00,  6.94s/it]